package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaseExecution generated by hbm2java
 */
@Entity
@Table(name = "case_execution", catalog = "musa_db")
public class CaseExecution implements java.io.Serializable {

	private Integer idCase;
	private Specification specification;
	private String name;
	private Date startedTime;
	private Date terminatedTime;
	private Set<CapabilityInstance> capabilityInstances = new HashSet<CapabilityInstance>(0);
	private Set<Variable> variables = new HashSet<Variable>(0);
	private Set<Predicate> predicates = new HashSet<Predicate>(0);

	public CaseExecution() {
	}

	public CaseExecution(Specification specification, String name, Date startedTime, Date terminatedTime,
			Set<CapabilityInstance> capabilityInstances, Set<Variable> variables, Set<Predicate> predicates) {
		this.specification = specification;
		this.name = name;
		this.startedTime = startedTime;
		this.terminatedTime = terminatedTime;
		this.capabilityInstances = capabilityInstances;
		this.variables = variables;
		this.predicates = predicates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCase", unique = true, nullable = false)
	public Integer getIdCase() {
		return this.idCase;
	}

	public void setIdCase(Integer idCase) {
		this.idCase = idCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSpecification")
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startedTime", length = 19)
	public Date getStartedTime() {
		return this.startedTime;
	}

	public void setStartedTime(Date startedTime) {
		this.startedTime = startedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "terminatedTime", length = 19)
	public Date getTerminatedTime() {
		return this.terminatedTime;
	}

	public void setTerminatedTime(Date terminatedTime) {
		this.terminatedTime = terminatedTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "caseExecution")
	public Set<CapabilityInstance> getCapabilityInstances() {
		return this.capabilityInstances;
	}

	public void setCapabilityInstances(Set<CapabilityInstance> capabilityInstances) {
		this.capabilityInstances = capabilityInstances;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "caseExecution")
	public Set<Variable> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable> variables) {
		this.variables = variables;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "caseExecution")
	public Set<Predicate> getPredicates() {
		return this.predicates;
	}

	public void setPredicates(Set<Predicate> predicates) {
		this.predicates = predicates;
	}

}
