package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DomainConfiguration generated by hbm2java
 */
@Entity
@Table(name = "domain_configuration", catalog = "musa_db")
public class DomainConfiguration implements java.io.Serializable {

	private Integer idDomainConfiguration;
	private Domain domain;
	private String name;
	private String value;
	private String description;

	public DomainConfiguration() {
	}

	public DomainConfiguration(Domain domain) {
		this.domain = domain;
	}

	public DomainConfiguration(Domain domain, String name, String value, String description) {
		this.domain = domain;
		this.name = name;
		this.value = value;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDomain_Configuration", unique = true, nullable = false)
	public Integer getIdDomainConfiguration() {
		return this.idDomainConfiguration;
	}

	public void setIdDomainConfiguration(Integer idDomainConfiguration) {
		this.idDomainConfiguration = idDomainConfiguration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idDomain", nullable = false)
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
