package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FunctionalReq generated by hbm2java
 */
@Entity
@Table(name = "functional_req", catalog = "musa_db")
public class FunctionalReq implements java.io.Serializable {

	private Integer idFunctionalReq;
	private Integer priority;
	private Process process;
	private Specification specification;
	private String name;
	private String type;
	private String description;
	private String currentState;
	private String body;
	private String actors;

	public FunctionalReq() {
	}

	public FunctionalReq(Process process, Specification specification,
			String name, String type, String description, String currentState,
			String body, String actors, Integer priority) {
		this.process = process;
		this.specification = specification;
		this.name = name;
		this.type = type;
		this.description = description;
		this.currentState = currentState;
		this.body = body;
		this.actors = actors;
		this.priority=priority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFunctional_Req", unique = true, nullable = false)
	public Integer getIdFunctionalReq() {
		return this.idFunctionalReq;
	}

	public void setIdFunctionalReq(Integer idFunctionalReq) {
		this.idFunctionalReq = idFunctionalReq;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idWF")
	public Process getProcess() {
		return this.process;
	}

	public void setProcess(Process process) {
		this.process = process;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idSpecification")
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "current_state", length = 29)
	public String getCurrentState() {
		return this.currentState;
	}

	public void setCurrentState(String currentState) {
		this.currentState = currentState;
	}

	@Column(name = "body")
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "actors")
	public String getActors() {
		return this.actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}
}
