package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Predicate generated by hbm2java
 */
@Entity
@Table(name = "predicate", catalog = "musa_db")
public class Predicate implements java.io.Serializable {

	private int idPredicate;
	private CaseExecution caseExecution;
	private byte[] name;
	private byte[] description;

	public Predicate() {
	}

	public Predicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	public Predicate(int idPredicate, CaseExecution caseExecution, byte[] name, byte[] description) {
		this.idPredicate = idPredicate;
		this.caseExecution = caseExecution;
		this.name = name;
		this.description = description;
	}

	@Id
	@Column(name = "idPredicate", unique = true, nullable = false)
	public int getIdPredicate() {
		return this.idPredicate;
	}

	public void setIdPredicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idCase")
	public CaseExecution getCaseExecution() {
		return this.caseExecution;
	}

	public void setCaseExecution(CaseExecution caseExecution) {
		this.caseExecution = caseExecution;
	}

	@Column(name = "name")
	public byte[] getName() {
		return this.name;
	}

	public void setName(byte[] name) {
		this.name = name;
	}

	@Column(name = "description")
	public byte[] getDescription() {
		return this.description;
	}

	public void setDescription(byte[] description) {
		this.description = description;
	}

}
