package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Process generated by hbm2java
 */
@Entity
@Table(name = "process", catalog = "musa_db")
public class Process implements java.io.Serializable {

	private Integer idWorkflow;
	private Specification specification;
	private String name;
	private String description;
	private byte[] fileWf;
	private Set<FunctionalReq> functionalReqs = new HashSet<FunctionalReq>(0);

	public Process() {
	}

	public Process(Specification specification, String name, String description, byte[] fileWf,
			Set<FunctionalReq> functionalReqs) {
		this.specification = specification;
		this.name = name;
		this.description = description;
		this.fileWf = fileWf;
		this.functionalReqs = functionalReqs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idWorkflow", unique = true, nullable = false)
	public Integer getIdWorkflow() {
		return this.idWorkflow;
	}

	public void setIdWorkflow(Integer idWorkflow) {
		this.idWorkflow = idWorkflow;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idSpecification")
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fileWF")
	public byte[] getFileWf() {
		return this.fileWf;
	}

	public void setFileWf(byte[] fileWf) {
		this.fileWf = fileWf;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "process")
	public Set<FunctionalReq> getFunctionalReqs() {
		return this.functionalReqs;
	}

	public void setFunctionalReqs(Set<FunctionalReq> functionalReqs) {
		this.functionalReqs = functionalReqs;
	}

}
