package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScenarioEvo generated by hbm2java
 */
@Entity
@Table(name = "scenario_evo", catalog = "musa_db")
public class ScenarioEvo implements java.io.Serializable {

	private Integer idScenarioEvo;
	private AbstractCapability abstractCapability;
	private String name;
	private String evolution;
	private String description;

	public ScenarioEvo() {
	}

	public ScenarioEvo(AbstractCapability abstractCapability, String name,
			String evolution, String description) {
		this.abstractCapability = abstractCapability;
		this.name = name;
		this.evolution = evolution;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idScenario_Evo", unique = true, nullable = false)
	public Integer getIdScenarioEvo() {
		return this.idScenarioEvo;
	}

	public void setIdScenarioEvo(Integer idScenarioEvo) {
		this.idScenarioEvo = idScenarioEvo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idAbstract_Cap")
	public AbstractCapability getAbstractCapability() {
		return this.abstractCapability;
	}

	public void setAbstractCapability(AbstractCapability abstractCapability) {
		this.abstractCapability = abstractCapability;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "evolution")
	public String getEvolution() {
		return this.evolution;
	}

	public void setEvolution(String evolution) {
		this.evolution = evolution;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
