package dbBean;

// Generated 3-mar-2017 14.31.46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "specification", catalog = "musa_db")
public class Specification implements java.io.Serializable {

	private Integer idSpecification;
	private Domain domain;
	private User user;
	private String name;
	private String description;
	private String state;
	private Set<FunctionalReq> functionalReqs = new HashSet<FunctionalReq>(0);
	private Set<CaseExecution> caseExecutions = new HashSet<CaseExecution>(0);
	private Set<NonFunctionalReq> nonFunctionalReqs = new HashSet<NonFunctionalReq>(
			0);
	private Set<Process> processes = new HashSet<Process>(0);

	public Specification() {
	}

	public Specification(Domain domain, User user, String name,
			String description, String state,
			Set<FunctionalReq> functionalReqs,
			Set<CaseExecution> caseExecutions,
			Set<NonFunctionalReq> nonFunctionalReqs, Set<Process> processes) {
		this.domain = domain;
		this.user = user;
		this.name = name;
		this.description = description;
		this.state = state;
		this.functionalReqs = functionalReqs;
		this.caseExecutions = caseExecutions;
		this.nonFunctionalReqs = nonFunctionalReqs;
		this.processes = processes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSpecification", unique = true, nullable = false)
	public Integer getIdSpecification() {
		return this.idSpecification;
	}

	public void setIdSpecification(Integer idSpecification) {
		this.idSpecification = idSpecification;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state", length = 27)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<FunctionalReq> getFunctionalReqs() {
		return this.functionalReqs;
	}

	public void setFunctionalReqs(Set<FunctionalReq> functionalReqs) {
		this.functionalReqs = functionalReqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<CaseExecution> getCaseExecutions() {
		return this.caseExecutions;
	}

	public void setCaseExecutions(Set<CaseExecution> caseExecutions) {
		this.caseExecutions = caseExecutions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<NonFunctionalReq> getNonFunctionalReqs() {
		return this.nonFunctionalReqs;
	}

	public void setNonFunctionalReqs(Set<NonFunctionalReq> nonFunctionalReqs) {
		this.nonFunctionalReqs = nonFunctionalReqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

}
