package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "musa_db")
public class User implements java.io.Serializable {

	private Integer idUser;
	private String name;
	private String password;
	private String role;
	private Set<ConcreteCapability> concreteCapabilities = new HashSet<ConcreteCapability>(0);

	public User() {
	}

	public User(String name, String role) {
		this.name = name;
		this.role = role;
	}

	public User(String name, String role, Set<ConcreteCapability> concreteCapabilities) {
		this.name = name;
		this.role = role;
		this.concreteCapabilities = concreteCapabilities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", nullable = false, length = 12)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<ConcreteCapability> getConcreteCapabilities() {
		return this.concreteCapabilities;
	}

	public void setConcreteCapabilities(Set<ConcreteCapability> concreteCapabilities) {
		this.concreteCapabilities = concreteCapabilities;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}
