package dbBean;

// Generated 1-mar-2017 16.50.58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable", catalog = "musa_db")
public class Variable implements java.io.Serializable {

	private Integer idVariable;
	private CaseExecution caseExecution;
	private String name;
	private String value;

	public Variable() {
	}

	public Variable(CaseExecution caseExecution, String name, String value) {
		this.caseExecution = caseExecution;
		this.name = name;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVariable", unique = true, nullable = false)
	public Integer getIdVariable() {
		return this.idVariable;
	}

	public void setIdVariable(Integer idVariable) {
		this.idVariable = idVariable;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idCase")
	public CaseExecution getCaseExecution() {
		return this.caseExecution;
	}

	public void setCaseExecution(CaseExecution caseExecution) {
		this.caseExecution = caseExecution;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
